### ISSUE TITLE
Error: C2-12828-1 | Crash by start | 

### ISSUE THREAD

**Issue by Trackelf** [fgsfdsfgs/max_vita#10]
[psp2core-1612104859-0x0000062b05-eboot.bin.zip](https://github.com/fgsfdsfgs/max_vita/files/5899953/psp2core-1612104859-0x0000062b05-eboot.bin.zip)

Please help me. :)
System:
PSV 2000 Enso 3.65
PSV2SD 
SD Card is ux0
Plugins are stored in ur0 internal 
<details>
  <summary>**config.txt**</summary>
  # This file is used as an alternative if ux0:tai/config.txt is not found.

# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/kubridgeskprx
ur0:tai/fd_fix.skprx
ur0:tai/storagemgr.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/reF00D.skprx
ur0:tai/repatch.skprx
ur0:tai/kubridge.skprx
ur0:tai/fd_fix.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/lolita444.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/videoDebug.skprx
ur0:/tai/CpuAffinityChanger.skprx
ur0:/tai/music_premium.skprx
ur0:/tai/noavls.skprx
ur0:/tai/AnalogsEnhancer.skprx
ur0:/tai/ioplus.skprx
ur0:/tai/kuio.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/download_enabler.suprx
ur0:tai/shellbat.suprx
ur0:tai/LowMemMode.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*ALL
ur0:/tai/FreePSM.suprx
ur0:/tai/FuckPSSE.suprx
ur0:/tai/reRescaler.suprx
ur0:/tai/vsh.suprx

</details>

Previous steps:

-Bought max payne @google app store. Bought it by amazon back in the day but the app isn't available there anymore.

-Installed Max Payne on my Phone

-Copy  Phone/sdcard/android/obb/com.rockstar.maxpayne/main.3.com.rockstar.maxpayne.obb file to pc
Downloaded 

-Downloaded MyAppSharer @android store, installed it and send the MaxPayne.apk to my pc

-Downloaded MaxPayne.vpk and Max.zip (Data Files) to my pc

-Downloaded PKGInstaller Launcher + PSM runtime Patches 1.00 + 2.00 + 2.10

-Downloaded fd_fix.skprx

Step 1:
Transferred kubridge.skprx to ux0:/tai/ and write "ur0:tai/kubridge.skprx" to my ur0:/tai/config.txt

Step 2: 
Transferred fd_fix.skprx to ux0:/tai/ and write "ur0:tai/fd_fix.skprx" to my ur0:/tai/config.txt

Step 3: 
Created a folder named "package" @ root of ux0 and transferred following files
"IP9100-PCSI00011_00-PSMRUNTIME000000.pkg"
"IP9100-PCSI00011_00-PSMRUNTIME000000-A0200-V0100-0c5cb04d07c9d9e135249594631feab513322db9-PE.pkg"
"IP9100-PCSI00011_00-PSMRUNTIME000000-A0201-V0100-e4708b1c1c71116c29632c23df590f68edbfc341-PE.pkg"
Transferred PKGInstallerLauncher.vpk to Vita and installed it
Making backup of my "ur0:/tai/config.txt" and deactivated all plugins
Runs PKGInstaller and installed the pkg in order like listed above
Reboot
Replaced the ur0:/tai/config.txt with my backup done before.
Reboot

Step 4:
Extracted the assets folder from your MaxPayne.apk to ux0:/data and rename it to maxpayne
Extracted lib/armeabi-v7a/libMaxPayne.so from your .apk to ux0:/data/maxpayne
Extracted the "main.3.com.rockstar.maxpayne.obb" file to "ux0:/data/maxpayne" with all content
Extracted the Max.zip (Data Folder) to "ux0:/data/" and replaced all files
Installed the MaxPayne_r3.vpk with vitashell 

Thank you for reading

**Comment by Rinnegatamante** [comment]
In the list you mentioned, you didn't run SharkF00D for the libshacccg.suprx extraction.

**Comment by Trackelf** [comment]
> 
> 
> In the list you mentioned, you didn't run SharkF00D for the libshacccg.suprx extraction.
?"?"?"?" 
Will you say that the   "How to build the master branch" Point is necessary?

**Comment by indianaliam1** [comment]
I don't even know what to do haha
