### ISSUE TITLE
Crashed at startup

### ISSUE THREAD

**Issue by Shiraki-kun** [fgsfdsfgs/max_vita#3]
[psp2core-1611941720-0x0000172d71-eboot.bin.zip](https://github.com/fgsfdsfgs/max_vita/files/5895350/psp2core-1611941720-0x0000172d71-eboot.bin.zip)

**Comment by fgsfdsfgs** [comment]
Did you extract data.zip after everything else and overwrite, like the installation instructions say? Did you get any prompts for overwriting at all? Show your maxpayne folder if not.

**Comment by Shiraki-kun** [comment]
I've rebuild my 'maxpayne' folder for now.

**Comment by fgsfdsfgs** [comment]
Well, tell me if it works or not. The crash dump you posted suggests that you didn't replace the shaders. Replacement shaders are in data.zip, so when you extract it, it will overwrite the old ones.

**Comment by Shiraki-kun** [comment]
> Well, tell me if it works or not. The crash dump you posted suggests that you didn't replace the shaders. Replacement shaders are in data.zip, so when you extract it, it will overwrite the old ones.

All the same.
![folderscreen4](https://user-images.githubusercontent.com/37235276/106310103-a69eb480-6295-11eb-81e4-aed38e4f358f.png)
![folderscreen3](https://user-images.githubusercontent.com/37235276/106310106-a7cfe180-6295-11eb-8d40-97f24ea2b9bf.png)
![folderscreen2](https://user-images.githubusercontent.com/37235276/106310109-a8687800-6295-11eb-9ae0-6592bbffd800.png)
![folderscreen1](https://user-images.githubusercontent.com/37235276/106310110-a9010e80-6295-11eb-93ba-f2deb07c1c4f.png)

**Comment by fgsfdsfgs** [comment]
That seems to be correct. Have you installed the runtime shader compiler? Like this stuff:
https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx

**Comment by Shiraki-kun** [comment]
> That seems to be correct. Have you installed the runtime shader compiler? Like this stuff:
> https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx
> 
> If you have, pay attention to the **Note 2** section at the bottom and try to do that.

Thanks, it works.
