### ISSUE TITLE
Crashed at startup

### ISSUE THREAD

**Issue by xRiseless** [fgsfdsfgs/max_vita#4]
Installed all stuff by instuction for 4-5 times, also do thing with ShaRKF00D (was read about this in #3) and gets crash after long black screen
[psp2core-1611943823-0x0000052cc3-eboot.bin.zip](https://github.com/fgsfdsfgs/max_vita/files/5895527/psp2core-1611943823-0x0000052cc3-eboot.bin.zip)

**Comment by xRiseless** [comment]
![image](https://user-images.githubusercontent.com/47669746/106312322-82cc7600-6277-11eb-973a-066676ad0027.png)
![image](https://user-images.githubusercontent.com/47669746/106312423-a8f21600-6277-11eb-96f5-313e2545d757.png)
![image](https://user-images.githubusercontent.com/47669746/106312477-c0310380-6277-11eb-8e11-7184599af896.png)

**Comment by fgsfdsfgs** [comment]
You're missing like half the files. All the .ras archives, for example.

**Comment by xRiseless** [comment]
> You're missing like half the files. All the .ras archives, for example. They should be next to the .so.

they must be in main maxpayne folder?

**Comment by fgsfdsfgs** [comment]
Yeah. Take a look at #3, that has screenshots of the correct layout.

**Comment by xRiseless** [comment]
It works! thanks!
