### ISSUE TITLE
Crash at startup.

### ISSUE THREAD

**Issue by GusTheProgrammer** [fgsfdsfgs/max_vita#5]
I checked the file directory according to the other issues opened
I installed kubridge.skprx to ur0:/tai with the rest of my other scripts (fdfix)
I also have libshacccg.suprx in  ur0:/data

![image](https://user-images.githubusercontent.com/51888440/106317398-30cf2480-6266-11eb-8644-3aba65cedabb.png)

[psp2core-1611947308-0x0000c231ab-eboot.bin.zip](https://github.com/fgsfdsfgs/max_vita/files/5895828/psp2core-1611947308-0x0000c231ab-eboot.bin.zip)

Thanks

**Comment by Rinnegatamante** [comment]
Try to manually delete ur0:data, recreate it and place inside it back libshacccg.suprx. Sometimes sharkf00d messes with folder privileges.

**Comment by fgsfdsfgs** [comment]
You could also have forgotten to reboot after installing kubridge.

**Comment by GusTheProgrammer** [comment]
A reboot fixed the issue, my bad
thanks for the help
