### ISSUE TITLE
game launch error

### ISSUE THREAD

**Issue by caritarock** [fgsfdsfgs/max_vita#6]
after doing the tutorial, I get this error when starting the game.

![WhatsApp Image 2021-01-29 at 21 27 23](https://user-images.githubusercontent.com/78233964/106324421-6598a700-6279-11eb-9cf2-05dca0f7d7a8.jpeg)

[psp2core-1611951134-0x0000014707-eboot.bin.zip](https://github.com/fgsfdsfgs/max_vita/files/5896190/psp2core-1611951134-0x0000014707-eboot.bin.zip)

**Comment by VitaHEX-Games** [comment]
Have you extracted the runtime shader compiler (libshacccg.suprx) from step 3?

**Comment by fgsfdsfgs** [comment]
Check the 3 closed issues on the same topic first, see if any of those help.

**Comment by caritarock** [comment]
thank you, I was missing the shading.
